engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - src/**/*
   - "**.js"
exclude_paths:
- __tests__/**/*
- node_modules/**/*
- public/**/*
- assets/**/*
