branch-defaults:
  close_and_escalate_message:
    environment: null
  develop:
    environment: provider
global:
  application_name: leo-provider
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
